import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./node_modules/flowbite/**/*.js",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/tw-elements/dist/js/**/*.js",
    "./src/**/*.{html,js,tsx,jsx,ts,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      backgroundImage: {
        "blooming-bg": "url('/images/blooming-bg.png')",
        "hero-bg": "url('/images/hero-bg.webp')",
        "hero2-bg": "url('/images/hero2-bg.webp')",
        "micheal-gouch": "url('/images/michael-gouch.png')",
        "web-design": "url('/images/web-design.webp')",
        "full-stack-apps": "url('/images/full-stack-apps.webp')",
        "mobile-apps": "url('/images/mobile-apps.png')",
        "e-commerce": "url('/images/e-commerce.webp')",
        "online-marketing": "url('/images/online-marketing.webp')",
        "creative-content": "url('/images/creative-content.webp')",
        "idea-bg": "url('/images/idea-bg.webp')",
        "newsletter-bg": "url('/images/newsletter.webp'')",
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  plugins: [require("flowbite/plugin"), require("tw-elements/dist/plugin")],
};
export default config;
